name: cosypose
channels:
   - conda-forge
   - pytorch
dependencies:
  - python=3.7.6
  - pinocchio=2.3.1
  - assimp=4.1.0
  - pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - torchvision=0.4.2=py37_cu101
  - rclone=1.52.3
  - gxx_linux-64=7.3.0
  - git-lfs=2.11.0
  - ffmpeg=4.2
  - bzip2=1.0.8
  - git=2.28.0
  - cmake=3.14.0
  - pip=19.3.1
  - numpy=1.17.4
  - pillow=6.0.0
  - ipython
  - pip:
      - ./deps/bullet3
      - ./deps/job-runner
      - imageio==2.6.1
      - simplejson==3.17.0
      - opencv-python==4.1.2.30
      - opencv-contrib-python==4.4.0.42
      - torchnet==0.0.4
      - tqdm==4.41.1
      - lxml==4.4.2
      - transforms3d==0.3.1
      - distributed==2.9.1
      - joblib==0.14.1
      - pandas==0.25.3
      - xarray==0.14.1
      - pyarrow==0.15.1
      - matplotlib==3.1.2
      - bokeh==1.4.0
      - plyfile==0.7.1
      - trimesh==3.5.16
      - pycollada==0.6
      - shapely==1.7.0
      - wget==3.2
      - pypng==0.0.20
      - PyOpenGL==3.1.0
      - Cython==0.29.21
      - glumpy==1.1.0
      - ipdb==0.12.3
      - colorama==0.4.3
      - scikit-video==1.1.11
      - scikit-image==0.16.2
      - scikit-learn==0.22.1
      - pyyaml==5.1
      - ipykernel==5.1.3
      - scipy==1.4.1
      - pywavefront==1.3.1
      - jupyter-client==5.3.4
      - jupyter-core==4.6.1
      - jupyter-server-proxy==1.5.0
      - jupyterlab==1.2.4
      - jupyterlab-server==1.0.6
